name: Upload Nightly
description: A GitHub Action to upload artifacts nightly
author: Your Name
version: 1.0.0

inputs:
  artifacts_path:
    description: 'Path to the artifacts directory'
    required: true
  project-name:
    description: 'Name of the project'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
